class Endpoints:
    # Effects
    EFFECTS             = "/effects"
    BRIGHTNESS          = EFFECTS + "/brightness"
    DARKNESS            = EFFECTS + "/darkness"
    GREYSCALE           = EFFECTS + "/greyscale"
    INVERT              = EFFECTS + "/invert"
    INVERTGREYSCALE     = EFFECTS + "/invertgreyscale"
    INVERTTHRESHOLD     = EFFECTS + "/invertThreshold"
    SEPIA               = EFFECTS + "/sepia"
    SILHOUETTE          = EFFECTS + "/silhouette"
    THRESHOLD           = EFFECTS + "/threshold"

    # Generators
    GENERATORS          = "/generators"
    ACHIEVEMENT         = GENERATORS + "/achievement"
    BAT_SLAP            = GENERATORS + "/batslap"
    BEAUTIFUL           = GENERATORS + "/beautiful"
    BLAME               = GENERATORS + "/blame"
    BOB_ROSS            = GENERATORS + "/bobross"
    CHALLENGER          = GENERATORS + "/challenger"
    CHANGE_MY_MIND      = GENERATORS + "/changemymind"
    COFFEE              = GENERATORS + "/coffee"
    COLOUR              = GENERATORS + "/colour"
    CONFUSED            = GENERATORS + "/confused"
    CRUSH               = GENERATORS + "/crush"
    FACEPALM            = GENERATORS + "/facepalm"
    FAN_SLAP            = GENERATORS + "/fanslap"
    GARBAGE             = GENERATORS + "/garbage"
    GIRLS               = GENERATORS + "/girls"
    HATES               = GENERATORS + "/hates"
    HEAVY_FEAR          = GENERATORS + "/heavyfear"
    HIDE                = GENERATORS + "/hide"
    IGNORE              = GENERATORS + "/ignore"
    KAREN               = GENERATORS + "/karen"
    KIRBY_SCHOOL        = GENERATORS + "/kirbyschool"
    MISSING             = GENERATORS + "/missing"
    PAINTING            = GENERATORS + "/painting"
    PLS                 = GENERATORS + "/pls"
    RELIGION            = GENERATORS + "/religion"
    RESPECT             = GENERATORS + "/respect"
    SNAPCHAT            = GENERATORS + "/snapchat"
    SNIPER              = GENERATORS + "/sniper"
    STEAM               = GENERATORS + "/steam"
    STEPPED             = GENERATORS + "/stepped"
    SUGGESTION_BOX      = GENERATORS + "/suggestion"
    SUPER_PUNCH         = GENERATORS + "/superpunch"
    SUPER_SPANK         = GENERATORS + "/superspank"
    TATTOO              = GENERATORS + "/tattoo"
    THE_SEARCH          = GENERATORS + "/thesearch"
    TIME                = GENERATORS + "/time"
    TINDER              = GENERATORS + "/tinder"
    TRIGGERED           = GENERATORS + "/triggered"
    VAULT               = GENERATORS + "/vault"
    VIRTUAL_REALITY     = GENERATORS + "/vr"
    WAIFU_INSULT        = GENERATORS + "/waifuinsult"
    WANTED              = GENERATORS + "/wanted"
    WRECK_IT            = GENERATORS + "/wreckit"
    ZERO_TWO_PICTURE    = GENERATORS + "/zerotwopicture"
    OSU                 = GENERATORS + "/osu"

    # Greetings
    GREETINGS           = "/greetings"
    UNIFIED_GREETINGS   = GENERATORS + "/unified"

    # Overlays
    OVERLAYS            = "/overlays"
    APPROVED            =  OVERLAYS + "/approved"
    DISCORD             =  OVERLAYS + "/discord"
    RAINBOW             =  OVERLAYS + "/rainbow"
    REJECTED            =  OVERLAYS + "/rejected"

    # Profile
    PROFILE             = "/profile"
    PROFILE_CARD        = PROFILE + "/profilecard"

    # Text
    TEXT                = "/text"
    CURSIVE             = TEXT + "/cursive"
    MOCK                = TEXT + "/mock"
    OWOIFY              = TEXT + "/owoify"
    TINY_TEXT           = TEXT + "/tiny_text"
    VAPORWAVE           = TEXT + "/vaporwave"